Add support for type of FUNDAMENTAL_GROUP
oscar-system/Polymake.jl pull request #386
Opened 2022-01-12 18:48 UTC by alexej-jordan

this required some small overhaul of lists, which previously only contained pairs of integers.

2022-01-13 09:09 UTC, kalmarek requested changes

2022-01-13 09:09 UTC, kalmarek commented on src/std/lists.jl
> +Base.eltype(::StdList{StdPair{S, T}}) where {S, T} = Pair{T,T}
```suggestion
Base.eltype(::StdList{StdPair{S, T}}) where {S, T} = Pair{S,T}
```

2022-01-13 09:09 UTC, kalmarek commented on src/std/lists.jl
> +function Base.iterate(L::StdList{T}) where T
why is `T` needed here?

2022-01-13 09:09 UTC, kalmarek commented on src/std/lists.jl
> +function Base.iterate(L::StdList{T}, state) where T
see above

2022-01-17 09:14 UTC, benlorenz approved these changes

2022-01-17 10:06 UTC, merged